### ISSUE TITLE
get error when use Recombee in java

### ISSUE THREAD

**Issue by ahmadazarnia** [Recombee/java-api-client#1]
Hi,I used the sample code in this repository,but when I run this line:
`client.send(new Batch(addUserRequests));`
I get this error:
 java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)

please help me...
thanks

**Comment by OndraFiedler** [comment]
Hi,
sorry for late reponse, I must have somehow overlooked the email :(
I just tried both examples using Java 8 (OpenJDK) and they worked for me.
Which version of Java do you use?
