### ISSUE TITLE
Java Instant support Jackson serelization

### ISSUE THREAD

**Issue by neee** [recombee/java-api-client#11]
Hello,
Need support java Instant (time module, for example: java 15)  I can't override or tune Jackson mapper for recombee client, cause this mapper is created inside the library code only.

Got errors like this:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Instant` not supported by default: add Module ""com.fasterxml.jackson.datatype:jackson-datatype-jsr310"" to enable handling (through reference chain: java.util.HashMap[""media""]->model.postgres.Media[""timeCreated""])"
```

If I add to the classpath required Jackson modules, I am not able to register them for the mapper object.

Let's add an extra constructor with an ObjectMapper argument?

**Comment by OndraFiedler** [comment]
Do I assume correctly that the issue appears on `SetItemValues` / `SetUserValues`?

Can't you just convert the `java.time.instant` value to `java.util.Date`?

**Comment by neee** [comment]
Yes my error related to SetItemValues method

**Comment by neee** [comment]
Your solution sounds good, but not modern, thanks
