### ISSUE TITLE
sample client statusCode 401

### ISSUE THREAD

**Issue by uguracar** [Recombee/java-api-client#2]
Hi,

I'm trying sample client, getting following error on the first request. Can you plz check?

client.send(new ResetDatabase());

Exception:
com.recombee.api_client.exceptions.ResponseException: {"statusCode":401, "error":"Invalid HMAC signature"}

**Comment by OndraFiedler** [comment]
Hi,

I could not reproduce your issue. Is it possible that you are using wrong credentials?
You have registered two accounts with very similar name (probably one contains a typo), so isn't it possible that you, for example, use wrong combination on `databaseId` and secret token?

**Comment by uguracar** [comment]
Thank you for your quick response, I was trying the api inside a spring boot application, I'll try pure example client and double check the dbid and secret token and let you know the result.

best regards
Ugur Acar

**Comment by uguracar** [comment]
there was a typo in the dbID, worked!, thanks again. 
Ugur

**Comment by OndraFiedler** [comment]
Great :)
