### ISSUE TITLE
valuesAreSet field always is false.

### ISSUE THREAD

**Issue by alepinzon** [recombee/java-api-client#3]
Hi, I'm trying to create a `RecommendItemsToUser` request  and set the `returnProperties`  to true, but the `valuesAreSet` field in the recommendation response always comes as false.

When i try to execute `recommendation.getValues()` it always throws an `IllegalStateException`.

I checked the response  body from the Api call and it does not contain the `valuesAreSet` property in the payload.

Recombee Api Response Payload:
`{"recommId": "8b904849-19ad-47d9-90f2-b024ca67726f", "recomms": [{"values": {"manufacturer_code": 1}, "id": "123"}]}`

Request:
```
        final RecommendItemsToUser cf = new RecommendItemsToUser("CF", 5)
                .setReturnProperties(true);
```

**Comment by OndraFiedler** [comment]
I confirm the bug, we will fix it ASAP

**Comment by alepinzon** [comment]
Thanks @OndraFiedler

**Comment by OndraFiedler** [comment]
It is fixed in https://github.com/recombee/java-api-client/releases/tag/v2.0.1.
The new version has been pushed to the central repository, but it can take some time (up to few hours) before it is available.
Thanks for reporting!
