### ISSUE TITLE
NoSuchMethod error related to encodeHexString

### ISSUE THREAD

**Issue by gallaghers18** [recombee/java-api-client#4]
I am using this api on an android app written in java, but I was getting the following error when trying to use client.send():

`java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)`

I ended up copying the source code into a local file so that I could edit it. I made the following small change that resulted in everything working.

Changed line 818 of RecombeeClient.java from `String sign = Hex.encodeHexString(rawHmac);` to `String sign = new String(Hex.encodeHex(rawHmac));.

I don't have the understanding of what all is going on here, but just wanted to let you know in case you wanted to investigate / change the source code.

**Comment by OndraFiedler** [comment]
Hi,

thank you for letting us know. Unfortunately, I am afraid that your usecase of Java SDK may not be entirely correct.
This Java SDK is intended for usage at backend servers, not at client side applications, such as Android apps.
Or can you somehow ensure that the secret token won't be spoiled?

We plan to develop an Android SDK with different authentication (weak token with limited capabilities), but I don't have any time estimate for it now.
