### ISSUE TITLE
com.recombee.api_client.exceptions.ResponseException: {"statusCode":401, "message":"Token has expired (Current time: 1557465110 or 2019-05-10 05:11:50 UTC, you are 209s off). Please synchronize your local time."}

### ISSUE THREAD

**Issue by gayathribanneheka** [recombee/java-api-client#5]
hi,
I'm trying to implement recombee to my jaca project. it gives following error code. please help..

com.recombee.api_client.exceptions.ResponseException: {"statusCode":401, "message":"Token has expired (Current time: 1557465110 or 2019-05-10 05:11:50 UTC, you are 209s off). Please synchronize your local time."}

	at com.recombee.api_client.RecombeeClient.checkErrors(RecombeeClient.java:879)
	at com.recombee.api_client.RecombeeClient.sendRequest(RecombeeClient.java:797)
	at com.recombee.api_client.RecombeeClient.send(RecombeeClient.java:332)
	at test.getResultsItemToItem(test.java:17)
	at test.main(test.java:38)

Thanks.

**Comment by OndraFiedler** [comment]
It says that time at your computer is off by 209 seconds and the requests cannot authenticated due to this issue. Setting correct time will fix the issue.
You can check accuracy of your local time also for example here: https://time.is/.
